
name: Amplify Deploy
on:
  push:
    branches:
      - main
    
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_DEFAULT_OUTPUT: json
        steps:
        - uses: actions/checkout@v2
        - name: Deploy
          run: |
            set $1 loginPOC
            set $2 main
            echo "Deploy app $1 branch $2"
            JOB_ID=$(aws amplify start-job --app-id $1 --branch-name $2 --job-type RELEASE | jq -r '.jobSummary.jobId')
            echo "Release started"
            echo "Job ID is $JOB_ID"
            
            while [[ "$(aws amplify get-job --app-id $1 --branch-name $2 --job-id $JOB_ID | jq -r '.job.summary.status')" =~ ^(PENDING|RUNNING)$ ]]; do sleep 1; done
            JOB_STATUS="$(aws amplify get-job --app-id $1 --branch-name $2 --job-id $JOB_ID | jq -r '.job.summary.status')"
            echo "Job finished"
            echo "Job status is $JOB_STATUS"
